//DEPENDENCIES
const inquirer = require ("inquirer");
const mysql = require ("mysql2");
const cTable = require('console.table');

//CONNECT TO DATABASE

//FUNCTION TO PROMPT USER FOR ACTION

//FUNCTION TO VIEW ALL EMPLOYEES

//FUNCTION TO VIEW ALL EMPLOYEES BY ROLES

//FUNCTION TO INCLUDE ROLES AS AN OPTION FOR THE ADD EMPLOYEE PROMPT

//FUNCTION TO ADD EMPLOYEE

//FUNCTION TO UPDATE EMPLOYEE RECORD

//FUNCTION TO ADD ROLE

//FUNCTION TO ADD A DEPARTMENT